# Generated by Django 3.0.7 on 2020-06-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_addreply_cr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=''),
        ),
    ]
